#
body:
  - type: markdown
    attributes:
      value: |
        Please enter details about any decision has been made without an RFC

        Fill out the following sections in as much detail as you can, then encourage others to join in.

  - type: dropdown
    id: Status
    attributes:
      label: What is the status of the decision
      options:
        - Proposed
        - Accepted
        - Rejected
        - Deprecated
        - Superceded
  - type: textarea
    attributes:
      label: Context
      description: What is the issue that we're seeing that is motivating this decision or change?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Decision
      description: |
        Why are we doing this? What use cases does it support? What is the expected outcome? What is the change that we're proposing and/or doing?

    validations:
      required: true
 
  - type: textarea
    attributes:
      label: Consequences
      description: What becomes easier or more difficult to do because of this change?
